In [61]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# np.intersect1d means return the unique values that are in both of input arrays
arr_distinct = np.intersect1d(a, b)
arr_distinct

array([2, 4])

In [54]:
#define arange form 1 to 16, len is 15. set 3 rows 5 columns then transpose to 5 rows 3 columns
np.arange(1,16).reshape(3,5).T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [55]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

# find the duplicate unique values from both arrays first
c = np.intersect1d(a, b) #print(c) array([ 3  5 12])
# find the values are in b array but not in duplicate array to filter to get the result
np.asarray([x for x in b if not x in c ])

array([14,  6, 11, 19])

In [63]:
# from google map, the total distance from NYC to Key West,FL by riding bike is 1519 miles
# create the array days dimention first which includes 35 days recording
arr_days = np.arange(1,36).reshape(35,1)
# create array miles which includes 31 days miles,insert random values
# normal function means the mean is 1519/31, variance is 1, size of values is 31
arr_miles = np.random.normal(1519/31,1,size=31)
# append 4 days record which have 0 miles due to the special situation
arr_miles = np.append(arr_miles,[0,0,0,0])
# permute the array miles, reshape it to be same as array days,round function means the result without demical
arr_miles = np.around(np.random.permutation(arr_miles).reshape(35,1))
# check if the total miles is enough to arrive
print(np.sum(arr_miles))
# hstack function means combine two arrays to be the completed record
np.hstack((arr_days,arr_miles))


1523.0


array([[ 1., 50.],
       [ 2., 50.],
       [ 3., 49.],
       [ 4., 49.],
       [ 5., 50.],
       [ 6.,  0.],
       [ 7., 49.],
       [ 8., 48.],
       [ 9., 46.],
       [10., 50.],
       [11., 48.],
       [12., 50.],
       [13., 48.],
       [14., 49.],
       [15., 49.],
       [16., 49.],
       [17., 50.],
       [18., 48.],
       [19., 49.],
       [20., 50.],
       [21.,  0.],
       [22., 50.],
       [23.,  0.],
       [24., 48.],
       [25., 49.],
       [26., 50.],
       [27., 49.],
       [28., 50.],
       [29., 49.],
       [30., 49.],
       [31., 52.],
       [32., 48.],
       [33., 48.],
       [34.,  0.],
       [35., 50.]])

In [57]:
import pandas

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').values
type(nyc_water) #print(nyc_water)
# find the max value of data, nyc_water[:,2] means find the index = 2 column 
max_NYC = np.max(nyc_water[:,2])
max_NYC

1512.0

In [58]:
# find the number of rows of the year, index = 0 is the year column
np.shape(nyc_water[:,0])

(39,)

In [59]:
# find mean of index = 3 (Capita column)
mean_perCap = np.mean(nyc_water[:,3])

# find mean of std = 3 (Capita column)
std_perCap = np.std(nyc_water[:,3])


print(mean_perCap)
print(std_perCap)

160.30769230769232
31.51894330370624


In [60]:
# diff data to array pop_diff
pop_diff = np.diff(nyc_water,axis = 0)[:,1]
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])